### ISSUE TITLE
i3blocks moved commands from `share` to `lib`

### ISSUE THREAD

**Issue by mkf** [XANi/uberstatus#4]

**Comment by XANi** [comment]
That path is not hardcoded in plugin in any way; and path will be distro-dependent anyway

**Comment by mkf** [comment]
Although it in fact may be distro-dependent, and it is not hardcoded in the i3blocks plugin, it is present in the default config file. If it was not distro-dependent but changed in some version of i3blocks, at least a comment would be appropiate. If it is a an Arch-specific thing though, there is not much sense for such a comment.
